[package]
name = "sparklytics-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
sparklytics-core = { path = "../sparklytics-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
